# Each card is a tuple of 2 words.
# word[0] = "primary" face (faces clockwise edge when placed)
# word[1] = "secondary" face (faces counter-clockwise edge when placed)
#
# Edge contributions by position:
#   NE edge: N.primary  +  E.secondary
#   SE edge: E.primary  +  S.secondary
#   SW edge: S.primary  +  W.secondary
#   NW edge: W.primary  +  N.secondary

WORD_CARDS = [
    ("OCEAN",     "WAVE"),
    ("CASTLE",    "MOAT"),
    ("LIGHTNING", "STORM"),
    ("HONEY",     "BEEHIVE"),
    ("CRYSTAL",   "JEWEL"),
    ("WOLF",      "HOWL"),
    ("CAPTAIN",   "ANCHOR"),
    ("PYRAMID",   "PHARAOH"),
    ("VAMPIRE",   "COFFIN"),
    ("DOCTOR",    "NEEDLE"),
    ("ROCKET",    "ORBIT"),
    ("GUITAR",    "MELODY"),
    ("LIBRARY",   "SCROLL"),
    ("COMPASS",   "DIRECTION"),
    ("WEAVER",    "SILK"),
    ("CANDLE",    "DARKNESS"),
    ("CROWN",     "SCEPTER"),
    ("FOSSIL",    "BONE"),
    ("TELESCOPE", "COMET"),
    ("POTION",    "CAULDRON"),
    ("PEARL",     "SHELL"),
    ("LANTERN",   "SHADOW"),
    ("FEATHER",   "QUILL"),
    ("CACTUS",    "SPINE"),
    ("HAMMER",    "ANVIL"),
    ("MIRROR",    "TWIN"),
    ("AVALANCHE", "MOUNTAIN"),
    ("GOBLIN",    "CAVE"),
    ("SYMPHONY",  "CONDUCTOR"),
    ("GLACIER",   "ICEBERG"),
    ("CHIMNEY",   "SMOKE"),
    ("THORN",     "PETAL"),
    ("BRIDGE",    "ARCH"),
    ("LIGHTHOUSE","BEACON"),
    ("SHIELD",    "ARMOR"),
    ("PRISM",     "SPECTRUM"),
    ("HOURGLASS", "SAND"),
    ("WHALE",     "SUBMARINE"),
    ("QUICKSAND", "TRAP"),
    ("OASIS",     "PALM"),
    ("ECHO",      "CANYON"),
    ("LAVA",      "CRATER"),
    ("PIRATE",    "PLANK"),
    ("WIZARD",    "ROBE"),
    ("CLOCK",     "GEAR"),
    ("MAZE",      "ENTRANCE"),
    ("LEMON",     "PEEL"),
    ("PHANTOM",   "MASK"),
    ("ECLIPSE",   "CORONA"),
    ("KNIGHT",    "LANCE"),
    ("RIVER",     "CURRENT"),
    ("FOREST",    "CANOPY"),
    ("VOLCANO",   "ERUPTION"),
    ("DESERT",    "DUNE"),
    ("ARCTIC",    "TUNDRA"),
    ("SWAMP",     "REED"),
    ("CLOAK",     "HOOD"),
    ("FORGE",     "BELLOWS"),
    ("THRONE",    "HERALD"),
    ("CHALICE",   "WINE"),
    ("LABYRINTH", "MINOTAUR"),
    ("ATLAS",     "GLOBE"),
    ("SERPENT",   "VENOM"),
    ("PHOENIX",   "ASHES"),
    ("GARGOYLE",  "CATHEDRAL"),
    ("SIREN",     "SHIPWRECK"),
    ("ORACLE",    "PROPHECY"),
    ("RAVEN",     "INK"),
    ("SCARECROW", "HARVEST"),
    ("LANYARD",   "BADGE"),
    ("BELFRY",    "BELL"),
    ("SUN",       "SUNFLOWER"),
    ("MOON",      "TIDE"),
    ("DRAGON",    "SCALES"),
    ("GRAVITY",   "FALL"),
    ("CAMERA",    "SMILE"),
    ("TRAIN",     "TRACKS"),
    ("CAMPFIRE",  "MARSHMALLOW"),
    ("BALLOON",   "HELIUM"),
    ("SOAP",      "BUBBLES"),
    ("ANCHOR",    "SHIP"),
    ("BREAD",     "TOAST"),
    ("BOOK",      "PAGES"),
    ("ICE",       "MELT"),
    ("KEY",       "LOCK"),
    ("COFFEE",    "MUG"),
    ("TREE",      "LEAF"),
    ("PIANO",     "KEYS"),
    ("DOG",       "LEASH"),
    ("BIRD",      "NEST"),
    ("SNAKE",     "SHED"),
    ("FARM",      "TRACTOR"),
    ("WIND",      "SAIL"),
    ("RAIN",      "UMBRELLA"),
    ("SNOW",      "FLAKE"),
    ("FIRE",      "ALARM"),
    ("STAR",      "GALAXY"),
    ("GOLD",      "MINE"),
    ("COAL",      "DIAMOND"),
    ("PAPER",     "CLIP"),
    ("PEN",       "WRITING"),
    ("PAINT",     "BRUSH"),
    ("STREET",    "SIGN"),
    ("CAR",       "TIRE"),
    ("WALL",      "BRICK"),
    ("TEA",       "BAG"),
    ("APPLE",     "CORE"),
    ("MILK",      "CARTON"),
    ("EGG",       "YOLK"),
    ("FISH",      "GILL"),
    ("CAT",       "WHISKER"),
    ("BEE",       "STING"),
    ("SPIDER",    "WEB"),
    ("CHAIR",     "CUSHION"),
    ("DOOR",      "KNOB"),
    ("WINDOW",    "GLASS"),
    ("SKY",       "CLOUD"),
    ("SHOE",      "LACE"),
    ("SHIRT",     "BUTTON"),
    ("PANTS",     "POCKET"),
    ("HAT",       "BRIM"),
    ("RING",      "FINGER"),
    ("GLASSES",   "FRAME"),
    ("WATCH",     "STRAP"),
    ("BAG",       "ZIPPER"),
]
