# Each card is a tuple of 4 words: (top, right, bottom, left)
# When placed on the board, words face the corresponding edge.
# "flipped" rotates the card 180°: top<->bottom, left<->right.
#
# Edge derivation (2×2 grid):
#   N edge = NW.top    + NE.top
#   E edge = NE.right  + SE.right
#   S edge = SW.bottom + SE.bottom
#   W edge = NW.left   + SW.left

WORD_CARDS = [
    ("OCEAN",     "REEF",     "WAVE",     "SHELL"),
    ("CASTLE",    "MOAT",     "DUNGEON",  "TOWER"),
    ("LIGHTNING", "THUNDER",  "STORM",    "CLOUD"),
    ("HONEY",     "BEEHIVE",  "NECTAR",   "BEAR"),
    ("CRYSTAL",   "JEWEL",    "DIAMOND",  "RING"),
    ("WOLF",      "MOON",     "HOWL",     "FOREST"),
    ("CAPTAIN",   "SHIP",     "ANCHOR",   "SAIL"),
    ("PYRAMID",   "SAND",     "PHARAOH",  "SPHINX"),
    ("VAMPIRE",   "BAT",      "COFFIN",   "NIGHT"),
    ("DOCTOR",    "PILL",     "NEEDLE",   "HOSPITAL"),
    ("ROCKET",    "STAR",     "ORBIT",    "PLANET"),
    ("GUITAR",    "STAGE",    "MELODY",   "CHORD"),
    ("LIBRARY",   "BOOK",     "SCROLL",   "SHELF"),
    ("COMPASS",   "MAP",      "DIRECTION","NORTH"),
    ("WEAVER",    "SPIDER",   "SILK",     "WEB"),
    ("CANDLE",    "WAX",      "DARKNESS", "FLAME"),
    ("CROWN",     "KING",     "SCEPTER",  "QUEEN"),
    ("FOSSIL",    "STONE",    "BONE",     "DINOSAUR"),
    ("TELESCOPE", "PLANET",   "COMET",    "SPACE"),
    ("POTION",    "BREW",     "CAULDRON", "WITCH"),
    ("PEARL",     "OYSTER",   "TIDE",     "DEEP"),
    ("LANTERN",   "LIGHT",    "SHADOW",   "DARK"),
    ("FEATHER",   "BIRD",     "QUILL",    "PEN"),
    ("CACTUS",    "DESERT",   "SPINE",    "FLOWER"),
    ("HAMMER",    "NAIL",     "ANVIL",    "FORGE"),
    ("MIRROR",    "GLASS",    "TWIN",     "REFLECTION"),
    ("AVALANCHE", "SNOW",     "MOUNTAIN", "SKI"),
    ("GOBLIN",    "TREASURE", "CAVE",     "RUMBLE"),
    ("SYMPHONY",  "ORCHESTRA","CONDUCTOR", "VIOLIN"),
    ("GLACIER",   "FROZEN",   "ICEBERG",  "ARCTIC"),
    ("CHIMNEY",   "HEARTH",   "SMOKE",    "BRICK"),
    ("THORN",     "ROSE",     "PETAL",    "GARDEN"),
    ("BRIDGE",    "RIVER",    "ARCH",     "ROAD"),
    ("LIGHTHOUSE","COAST",    "BEACON",   "SIGNAL"),
    ("SHIELD",    "BATTLE",   "ARMOR",    "SWORD"),
    ("PRISM",     "RAINBOW",  "SPECTRUM", "COLOR"),
    ("HOURGLASS", "TIME",     "GRAINS",   "CLOCK"),
    ("WHALE",     "OCEAN",    "SUBMARINE","FISH"),
    ("QUICKSAND", "TRAP",     "MUD",      "DANGER"),
    ("OASIS",     "WATER",    "PALM",     "DESERT"),
    ("ECHO",      "SOUND",    "CANYON",   "VOICE"),
    ("LAVA",      "MAGMA",    "CRATER",   "VOLCANO"),
    ("PIRATE",    "TREASURE", "PLANK",    "CANNON"),
    ("WIZARD",    "MAGIC",    "ROBE",     "STAFF"),
    ("CLOCK",     "TICK",     "GEAR",     "ALARM"),
    ("MAZE",      "PUZZLE",   "ENTRANCE", "EXIT"),
    ("LEMON",     "SOUR",     "PEEL",     "FRUIT"),
    ("PHANTOM",   "GHOST",    "MASK",     "HAUNTED"),
    ("ECLIPSE",   "SHADOW",   "CORONA",   "SUN"),
    ("KNIGHT",    "CASTLE",   "LANCE",    "HORSE"),
    ("RIVER",     "FISH",     "CURRENT",  "STREAM"),
    ("FOREST",    "TREE",     "CANOPY",   "LEAF"),
    ("VOLCANO",   "LAVA",     "ERUPTION", "ASH"),
    ("DESERT",    "CACTUS",   "DUNE",     "SUN"),
    ("ARCTIC",    "POLAR",    "TUNDRA",   "ICE"),
    ("SWAMP",     "FROG",     "REED",     "MUD"),
    ("CLOAK",     "HIDDEN",   "HOOD",     "SHADOW"),
    ("FORGE",     "METAL",    "BELLOWS",  "FIRE"),
    ("THRONE",    "ROYAL",    "HERALD",   "PALACE"),
    ("CHALICE",   "TOAST",    "WINE",     "FEAST"),
    ("LABYRINTH", "MYTH",     "MINOTAUR", "CREEK"),
    ("ATLAS",     "WORLD",    "GLOBE",    "OCEAN"),
    ("SERPENT",   "VENOM",    "FANG",     "SCALE"),
    ("PHOENIX",   "REBIRTH",  "ASHES",    "FLAME"),
    ("GARGOYLE",  "STONE",    "CATHEDRAL","ROOF"),
    ("SIREN",     "MERMAID",  "SHIPWRECK","SONG"),
    ("ORACLE",    "TEMPLE",   "PROPHECY", "FUTURE"),
    ("RAVEN",     "FEATHER",  "INK",      "PAPER"),
    ("SCARECROW", "FARM",     "HARVEST",  "CROW"),
    ("LANYARD",   "CAMP",     "BADGE",    "TENT"),
    ("BELFRY",    "CHURCH",   "BELL",     "TOWER"),
    ("SUN",       "SKY",      "SUNFLOWER","SHINE"),
    ("MOON",      "NIGHT",    "TIDE",     "STAR"),
    ("DRAGON",    "FIRE",     "SCALES",   "WING"),
    ("GRAVITY",   "SPACE",    "FALL",     "APPLE"),
    ("CAMERA",    "PHOTO",    "SMILE",    "LENS"),
    ("TRAIN",     "STEAM",    "TRACKS",   "CABOOSE"),
    ("CAMPFIRE",  "WOOD",     "MARSHMALLOW","TOAST"),
    ("BALLOON",   "PARTY",    "HELIUM",   "FLOAT"),
    ("SOAP",      "CLEAN",    "BUBBLES",  "FOAM"),
    ("ANCHOR",    "PORT",     "CHAIN",    "DOCK"),
    ("BREAD",     "OVEN",     "CRUST",    "BUTTER"),
    ("BOOK",      "READ",     "PAGES",    "STORY"),
    ("ICE",       "FREEZE",   "MELT",     "WATER"),
    ("KEY",       "DOOR",     "LOCK",     "GOLD"),
    ("COFFEE",    "MORNING",  "MUG",      "BEAN"),
    ("TREE",      "ROOT",     "BARK",     "BRANCH"),
    ("PIANO",     "MUSIC",    "KEYS",     "SONG"),
    ("DOG",       "BONE",     "LEASH",    "BARK"),
    ("BIRD",      "WING",     "NEST",     "EGG"),
    ("SNAKE",     "GRASS",    "SHED",     "VENOM"),
    ("FARM",      "BARN",     "TRACTOR",  "CROP"),
    ("WIND",      "GUST",     "BREEZE",   "SAIL"),
    ("RAIN",      "CLOUD",    "UMBRELLA", "PUDDLE"),
    ("SNOW",      "COLD",     "FLAKE",    "ICE"),
    ("FIRE",      "HEAT",     "ALARM",    "SMOKE"),
    ("STAR",      "NIGHT",    "GALAXY",   "SHINE"),
    ("GOLD",      "FORTUNE",  "MINE",     "COIN"),
    ("COAL",      "BLACK",    "DIAMOND",  "MINE"),
    ("PAPER",     "NOTE",     "CLIP",     "SCISSORS"),
    ("PEN",       "BLUE",     "WRITING",  "INK"),
    ("PAINT",     "ART",      "BRUSH",    "CANVAS"),
    ("STREET",    "CITY",     "SIGN",     "LAMP"),
    ("CAR",       "GARAGE",   "TIRE",     "ENGINE"),
    ("WALL",      "HOUSE",    "BRICK",    "WINDOW"),
    ("TEA",       "LEAF",     "BAG",      "CUP"),
    ("APPLE",     "ORCHARD",  "CORE",     "STEM"),
    ("MILK",      "COW",      "CARTON",   "GLASS"),
    ("EGG",       "CHICKEN",  "YOLK",     "SHELL"),
    ("FISH",      "HOOK",     "GILL",     "NET"),
    ("CAT",       "PURR",     "WHISKER",  "PAW"),
    ("BEE",       "FLOWER",   "STING",    "HIVE"),
    ("SPIDER",    "SILK",     "WEB",      "FLY"),
    ("CHAIR",     "SEAT",     "CUSHION",  "TABLE"),
    ("DOOR",      "WELCOME",  "KNOB",     "HALL"),
    ("WINDOW",    "VIEW",     "GLASS",    "BLIND"),
    ("SKY",       "BLUE",     "CLOUD",    "BIRD"),
    ("SHOE",      "FOOT",     "LACE",     "SOCK"),
    ("SHIRT",     "WEAR",     "BUTTON",   "COLLAR"),
    ("PANTS",     "LEG",      "POCKET",   "BELT"),
    ("HAT",       "HEAD",     "BRIM",     "FEATHER"),
    ("RING",      "LOVE",     "FINGER",   "GEM"),
    ("GLASSES",   "SEE",      "FRAME",    "LENS"),
    ("WATCH",     "TIME",     "STRAP",    "WRIST"),
    ("BAG",       "CARRY",    "ZIPPER",   "POUCH"),
]
