# Generated by Django 4.2.29 on 2026-03-17 16:40

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('status', models.CharField(default='lobby', max_length=20)),
                ('current_clover_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=40)),
                ('is_host', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
            options={
                'unique_together': {('room', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='Clover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('clues_submitted', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clover', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('submitted', models.BooleanField(default=False)),
                ('clover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.clover')),
                ('guesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses_made', to='game.player')),
            ],
            options={
                'unique_together': {('guesser', 'clover')},
            },
        ),
    ]
