# Generated by Django 4.2.29 on 2026-06-20 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
