# Generated by Django 6.0.6 on 2026-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='session_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('writing', 'Writing'), ('guessing', 'Guessing'), ('scoring', 'Scoring'), ('finished', 'Finished')], default='lobby', max_length=20),
        ),
    ]
